# Generated by Django 3.0.2 on 2020-02-29 22:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_delete_value'),
    ]

    operations = [
        migrations.AlterField(
            model_name='monthlydonation',
            name='monthly_donation',
            field=models.FloatField(),
        ),
    ]
