# Generated by Django 3.0.2 on 2020-02-29 23:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_auto_20200229_2252'),
    ]

    operations = [
        migrations.AddField(
            model_name='monthlydonation',
            name='title',
            field=models.CharField(default='donation amount', max_length=100),
        ),
        migrations.AlterField(
            model_name='monthlydonation',
            name='monthly_donation',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=8),
        ),
    ]
