# Generated by Django 3.0.2 on 2020-03-01 22:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_auto_20200301_0004'),
    ]

    operations = [
        migrations.AlterField(
            model_name='monthlydonation',
            name='amount',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=8),
        ),
    ]
