# Generated by Django 3.0.2 on 2020-02-01 22:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cause',
            name='pub_date',
        ),
        migrations.AlterField(
            model_name='cause',
            name='title',
            field=models.CharField(max_length=100),
        ),
    ]
