# Generated by Django 3.0.2 on 2020-02-29 20:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cause',
            name='value',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
    ]
