# Generated by Django 3.0.2 on 2020-02-29 20:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0002_cause_value'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cause',
            old_name='value',
            new_name='category',
        ),
    ]
