# Generated by Django 3.0.2 on 2020-02-28 05:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('accounts', '0002_auto_20200226_2009'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='monthly_donation',
        ),
        migrations.CreateModel(
            name='MonthlyDonation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('monthly_donation', models.DecimalField(decimal_places=2, default=0.0, max_digits=8)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_donation', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
