# Generated by Django 3.0.2 on 2020-02-28 06:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_auto_20200228_0510'),
    ]

    operations = [
        migrations.RenameField(
            model_name='value',
            old_name='title',
            new_name='value',
        ),
    ]
