# Generated by Django 3.0.2 on 2020-02-28 19:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_valuechoice'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ValueChoice',
        ),
    ]
