# Generated by Django 3.0.2 on 2020-02-29 01:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_delete_valuechoice'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Value',
        ),
    ]
